apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 390421316924.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 390421316924.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
